name: Java CI with Gradle & Allure Reporting

on:
  workflow_dispatch:
    inputs:
      suite:
        description: Select the test suite to run
        required: true
        default: sauce-lab-suite
        type: choice
        options:
          - sauce-lab-suite
      browser:
        description: Select the browser to run tests
        required: true
        default: chrome
        type: choice
        options:
          - chrome
          - firefox
          - edge
          - chrome_docker

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

#      - name: Setup Chrome
#        uses: browser-actions/setup-chrome@v1.7.2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0

      - name: Build and Test with Gradle
        run: ./gradlew test -Dtestng.suite=src/test/resources/suits/${{ github.event.inputs.suite }}.xml -Dbrowser=${{ github.event.inputs.browser }}

      - name: Checkout gh-pages
        if: always()
        uses: actions/checkout@v4.1.7
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report with History
        if: always()
        uses: simple-elf/allure-report-action@v1.9
#        id: allure-report
        with:
          allure_results: build/allure-results
#          gh_pages: gh-pages
#          allure_report: build/reports/allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Generate and Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v3